### ISSUE TITLE
German App title and description in Google Play Store not reflecting the new name AdGuard / App title wrong

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#109]
@sergerosenthaler commented on [Thu Mar 08 2018](https://github.com/AdguardTeam/AdguardForAndroid/issues/1761)

![2018-03-08_13-25-20](https://user-images.githubusercontent.com/25068100/37151211-d4aa4f6e-22d4-11e8-9b6b-18a6a75da2cd.png)

**Comment by sergerosenthaler** [comment]
@ameshkov regarding the App title. Make sure to use either "AdGuard-Inhaltsblocker" or "AdGuard Inhaltsblocker" (App and adguard.com). I would recommend to use AdGuard-Inhaltsblocker because all products with extra names like the browser extension at the moment use a "-". This should be reflected in the Glossary on OneSky.

**Comment by ameshkov** [comment]
@aalpatkina plz take note

**Comment by nkartyshov** [comment]
done
