### ISSUE TITLE
Prepare release 1.0.7

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#77]
https://github.com/AdguardTeam/ContentBlocker/milestone/6

Create a release notes draft here.
Attach both release apks (cb16, cb21) to it.
Let @nkartyshov know so that he could upload it to Google Play and Galaxy Store.

**Comment by seanl-adg** [comment]
**[Fixed] Browsers are not notified when we auto-update filters [#69](https://github.com/AdguardTeam/ContentBlocker/issues/69)**

Previously, there was a bug that filter updates that happens at background were not applied to browsers. This update fixes it.

[Changed] Make "Safari filter" enabled by default in the Content Blocker [#65](https://github.com/AdguardTeam/ContentBlocker/issues/65)

Due to difference adblocking methods we use in different platforms, we provide different filters for each platforms. Until now, there was no special filter for Adguard Content Blocker. The ad blocking extensions provided by Samsung browser and Yandex browser is close to that of Safari, so we decided to enable Safari filter by default. Filter categorization is on the way of change, so the name of the filter which is a bit unfit for content blocker will be changed.

[Improved] Feedback/Contact Us option [#76](https://github.com/AdguardTeam/ContentBlocker/issues/76)

**Comment by ameshkov** [comment]
@seanl-adg please create a release draft and attach the apk files once you merge the pull request

**Comment by nkartyshov** [comment]
@seanl-adg I published new version in stores. You can close your tasks.
